name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  checks: write
  pull-requests: write

jobs:
  ci:
    runs-on: ubuntu-latest
    name: CI for Pull Request
    steps:
    - name: Checkout the source code
      uses: actions/checkout@v3
      with:
        path: src/src

    - name: CI
      uses: pv/bluez-action-ci@kvm
      with:
        task: ci
        base_folder: src
        space: user
        github_token: ${{ secrets.GITHUB_TOKEN }}
        email_token: "TEST_TOKEN"
        patchwork_token: "TEST_TOKEN"
        patchwork_user: "1234"
